### ISSUE TITLE
need hints/gelp for configuring fm10k to be able to pass traffic

### ISSUE THREAD

**Issue by mradam79** [jrfastab/match-interface#3]
This is what I have: 2 PCs running Linux 4.4.13, each with a FM10420 card, produced by Silicom.
I loaded the driver fm10k-0.21.7 from sourceforge, IES version 4.3 and latest version of match-interfaces.
I have a configuration file fm_platform_attributes.cfg of which I'm confident it is complete.

The goal is to be able to send traffic between the 2 PCs using the FM10420 cards at 100Gbps.
I managed to get the link up on both sides, when I send packets from one side, the tx_packets gets incremented but the peer does not see the packets (even its rx_packets counter won't increase).
The traffic sent between the 2 PCs is ARP.

Please provide some hints on what should be the simplest / correct process.
I would prefer to use the fm10k driver embedded in Linux kernel tree to avoid using UIO.

Thanks in advance for any pointers.

**Comment by jrfastab** [comment]
Interesting. So couple points, this github repository is 'just' my development branch and I don't have any idea what has changed between my version here and the latest IES version 4.3. One guess is because I never tested it there are some hardware setting that are not being configured. I have not actively worked on this for months.

I think the best way to get this figured out is to email the list with the developers who are actively working on this. Can you send an email to 'intel-wired-lan@lists.osuosl.org' with the above details? They should be able to give you a set of tested version of code. Please CC me if possible.

Thanks,
John

**Comment by mradam79** [comment]
I CC-ed you in my email to Intel Wired LAN team and will post the relevant answer from them here as well.
BTW, you mentioned this repository being your development branch. Could you please point to the release branch supposedly backed by Intel?

Thanks!
